### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by gsemino**
Updated README.md to include proper syntax for composer.json, added brackets around require syntax

### CODE REVIEW

**Comment by gsemino** [comment]
added brackets for require syntax for composer.json

**Comment by gsemino** [comment]
@Jeger , hello Halvard, when you have a chance can you review this? I added this after I installed php sdk myself and saw the require needed extra brackets

**Comment by Jeger** [comment]
Thanks for fixing it :)

**Comment by gsemino** [comment]
No problem :)

**Pull request merged**
